# Generated by Django 4.0 on 2021-12-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('admin_site_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FAQ_user', to='user_management.user'),
        ),
        migrations.AddField(
            model_name='contact',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_user', to='user_management.user'),
        ),
    ]
