# Generated by Django 4.0 on 2021-12-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=200)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('collection_description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_name', models.CharField(max_length=200)),
                ('nft_description', models.TextField(blank=True, null=True)),
                ('nft_image', models.ImageField(upload_to='')),
                ('royalty', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('sale_type', models.CharField(blank=True, choices=[('is_put_on_sale', 'Is Put On Sale'), ('is_instant_sale_price', 'Is Instant Sale Price'), ('is_unlock_purchase', 'Is Unlock Purchase')], max_length=40, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('total_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NftPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, choices=[('fake', 'Fak or spam'), ('explicit', 'Explicit and Sensitive Content'), ('might_be_stolen', 'Might be Stolen'), ('other', 'Other')], max_length=40, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('nft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_nft', to='nft_management.nft')),
            ],
        ),
    ]
