# Generated by Django 4.0 on 2021-12-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('nft_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportednft',
            name='reporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='user_management.user'),
        ),
        migrations.AddField(
            model_name='nftpricehistory',
            name='nft_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_history', to='nft_management.nft'),
        ),
        migrations.AddField(
            model_name='nft',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_collection', to='nft_management.collection'),
        ),
        migrations.AddField(
            model_name='nft',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_owner', to='user_management.user'),
        ),
        migrations.AddField(
            model_name='favouritenft',
            name='nft_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_nft', to='nft_management.nft'),
        ),
        migrations.AddField(
            model_name='favouritenft',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite', to='user_management.user'),
        ),
        migrations.AddField(
            model_name='collection',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nft_category', to='nft_management.category'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to='user_management.user'),
        ),
    ]
