# Generated by Django 4.0 on 2021-12-14 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('wallet_management', '0001_initial'),
        ('nft_management', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.FloatField()),
                ('sold_date', models.DateTimeField(auto_now=True)),
                ('service_fee', models.FloatField(default=0)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nft_buyer', to='user_management.user')),
                ('nft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_transaction', to='nft_management.nft')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nft_seller', to='user_management.user')),
                ('wallet_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='wallet_management.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_date', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('nft_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_nft', to='nft_management.nft')),
                ('offer_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_biding', to='user_management.user')),
            ],
        ),
    ]
